@startuml
'https://plantuml.com/use-case-diagram

:traveller: as tr
:user:
:guide: as gu
:Agency: as ag
gu -[hidden]-> ag
tr -[hidden]-> ag
:user: -[hidden]-> ag
tr <|-- :user:
gu <|-- :user:

:user: --> (Manage profile)
:user: --> (Choose actor)

tr --> (cancel booking)
tr --> (view trips)
tr --> (booking trip)
tr --> (set filters)
tr --> (leave a review) : trip already completed

(set filters) ..> (view trips) : extend
(booking trip) ..> (view trips) : include
(booking trip) ..> (payment) : include

(edit review) ..> (leave a review) : extend
(cancel booking) -[hidden]-> (edit review)
(Notify guide) as ngt
(Notify agency) as nat
(leave a review) ..> ngt : include
(leave a review) ..> nat : include

gu --> (Send application)
gu --> (Add skills)
gu --> (Add preferences)
gu --> (View trips)
gu --> (withdraw application)

(View trips) ..> (Manage preferences) : extend
(View trips) ..> (Manage skills) : include
(withdraw application) ..> (Notify agency) : include

ag --> (Manage guide)
ag --> (create trip)
ag --> (delete trip)
ag --> (edit trip)

(delete trip) ..> (Notify guide) : include
(edit trip) ..> (Notify guide) : include
(delete trip) ..> (Notify traveller) : include
(edit trip) ..> (Notify traveller): include

@enduml