@startuml
'https://plantuml.com/use-case-diagram

:traveller: as tr
:Unqualified:
:guide: as gu
:Agency: as ag

:Unqualified: --> (Manage profile)
:Unqualified: --> (Choose role)

tr --> (cancel booking)
tr --> (view trips)
tr --> (booking trip)
tr --> (set filters)
tr -left-> (leave a review) : trip already completed

(view trips) ..>(set filters) : extend
(booking trip) ..> (view trips) : include
(booking trip) ..> (payment) : include

(edit review) ..> (leave a review) : extend
(cancel booking) -[hidden]-> (edit review)
(Notify guide) as ngt
(Notify agency) as nat
(leave a review) ..> ngt : include
(leave a review) ..> nat : include

gu --> (Send application)
gu --> (Add skills)
gu --> (Add preferences)
gu --> (View trips)
gu --> (withdraw application)

(View trips) ..> (Manage preferences) : extend
(View trips) ..> (Manage skills) : include
(withdraw application) ..> (Notify agency) : include

ag --> (Manage guide)
ag --> (create trip)
ag --> (delete trip)
ag --> (edit trip)

(delete trip) ..> (Notify guide) : include
(edit trip) ..> (Notify guide) : include
(delete trip) ..> (Notify traveller) : include
(edit trip) ..> (Notify traveller): include

@enduml